### ISSUE TITLE
Grade entry error should be removed when the error is removed/corrected.

### ISSUE THREAD

**Issue by jamiefolsom** [mitodl/edx-sga#121]
Across show/hide, and across changing/removing grade values, an error (too high, low, NaN, etc), persists. It should be removed when the error is removed or corrected. The screenshot shows the error persisting on an assignment from which the grade has been removed.

![screen shot 2015-08-27 at 12 03 15 pm](https://cloud.githubusercontent.com/assets/882377/9525796/da3cf57a-4cb3-11e5-802c-01b0e86afb22.png)

**Comment by pdpinch** [comment]
Duplicate of #108 

although perhaps with a clearer title

**Comment by jamiefolsom** [comment]
Ah, thx.
