### ISSUE TITLE
"Duplicate" error when installing per instructions

### ISSUE THREAD

**Issue by danielmcquillen** [mitodl/edx-sga#142]
I experimented today with installing edx-sga on a new devstack (based on dogwood).

I'm pretty sure I followed your devstack instructions correctly, but when I try to run the lms, I get 

`Traceback (most recent call last):
  File "manage.py", line 112, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/cms/startup.py", line 31, in run
    django.setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: edx_sga`

Interestingly, I see the following code in common.py for both the lms and cms:

`OPTIONAL_APPS = (
    'mentoring',
    'problem_builder',
    'edx_sga',
`

Could it be that now we now don't have to add edx_sga to the ADDL_INSTALLED_APPS property in the lms and cms env.json files ?

If so, are the correct instructions just to pip install edx-sga and it's ready to go? This was the case for me.

Thanks!

**Comment by pdpinch** [comment]
We have (finally) updated the ReadMe to address this issue.
