### ISSUE TITLE
Refactor to use submissions app

### ISSUE THREAD

**Issue by jetej** [mitodl/edx-sga#16]
See https://github.com/edx/edx-submissions and the corresponding post on the edx-code mailing list: https://groups.google.com/forum/#!searchin/edx-code/submission/edx-code/YrcP2770L3I/wqGkbpN7noQJ

Using submissions will avoid the current requirement that students re-visit the SGA problem in order to have their grade recorded.

(See https://github.com/jazkarta/edx-sga/issues/21)

**Comment by pdpinch** [comment]
This will be addressed in the 0.4.0 release
