### ISSUE TITLE
Add support for django 1.11 (but continue to support django 1.8)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#167]
The Hawthorn release of edx-platform will require django 1.11

**Comment by doctoryes** [comment]
The relevant tickets:
https://openedx.atlassian.net/browse/PLAT-1592
https://openedx.atlassian.net/browse/PLAT-1640

**Comment by macdiesel** [comment]
FYI the plan is to have all libraries for edx-platform support both Django 1.8 and 1.11 for the Django 1.11 upgrade. Once the upgrade has completed any shims that may have been necessary for continued 1.8 may be removed.

**Comment by pdpinch** [comment]
Ah, thanks. Django 1.8 support seems important. I updated the issue title.

**Comment by pdpinch** [comment]
@amir-qayyum-khan with PR #174 close this?

**Comment by amir-qayyum-khan** [comment]
it need to rebase it, and present it for review

**Comment by pdpinch** [comment]
@amir-qayyum-khan Now that #174 has merged, what else do we need to do?

I presume we need a release to PyPI? 

FYI @doctoryes @macdiesel

**Comment by amir-qayyum-khan** [comment]
@pdpinch this is complete, our tox setup run these test on Django version 1.8 to the latest version
https://github.com/mitodl/edx-sga/blob/master/tox.ini#L9
