### ISSUE TITLE
Timezone handling is incorrect

### ISSUE THREAD

**Issue by noisecapella** [mitodl/edx-sga#204]
This was introduced in https://github.com/mitodl/edx-sga/pull/169#issuecomment-339054815
We should use `datetime.now(tz=timezone)` instead of `datetime.utcnow().replace(tzinfo=timezone)`. The latter will use the UTC time with the `timezone` timezone which results in the incorrect time

**Comment by pdpinch** [comment]
Moving this into ready

**Comment by noisecapella** [comment]
I think the proper behavior here is to always handle timestamps as UTC. That's what the XBlock field seems to expect: https://github.com/edx/XBlock/blame/master/xblock/fields.py#L944

I'm going to make a PR to revert that change. Regarding the original use case for #169, it looks like there is a Django template function [django.utils.timezone.activate](https://docs.djangoproject.com/ko/1.11/topics/i18n/timezones/#selecting-the-current-time-zone) which will set the timezone for the purpose of rendering in a template
