### ISSUE TITLE
"Delete Learner's State" doesn't remove the users submission

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#214]
As an instructor, I sometimes need to delete the learner's submission so they can attempt the problem again. This is often in response to a technical issue or similar. 

In an SGA block, when I delete the student state, I get a success message, but the learner's submission is still visible and they can't submit again.

**Comment by pdpinch** [comment]
I believe SGA currently renders its own "Staff Debug Info" button, in addition to the one that appears after every XBlock. The SGA-internal one doesn't appear to have the "Delete Learner's State" function at all. 

If this feature can be made to work in the generic "Staff Debug Info", then the SGA-internal one could be removed from edx-sga. I suspect however that we will require some SGA-specific context in order to make "Delete Learner's State" functional.

**Comment by pdpinch** [comment]
@gsidebo are you working on this?

**Comment by gsidebo** [comment]
yes this is next on my list

**Comment by pdpinch** [comment]
I am told that this works as expected in the ORA2 XBlock https://github.com/edx/edx-ora2 -- if possible, it would be good to follow their pattern.

**Comment by pdpinch** [comment]
Looks like this is the relevant method: https://github.com/edx/edx-ora2/blob/65ebba350e7edfac19edd49052de9559ad16191b/openassessment/xblock/staff_area_mixin.py#L397

**Comment by gsidebo** [comment]
Yup, I implemented that method in SGA last night. What I'm still confused about is another side effect of clearing the student's state which happens in LMS
