### ISSUE TITLE
Clearing a student's state does not cause the submission zip file to be created again

### ISSUE THREAD

**Issue by gsidebo** [mitodl/edx-sga#224]
To reproduce: 

1. Upload a submission for an SGA problem with a couple different users
1. Click "Download All Submissions" in the staff view to create a new submission zip file
1. Clear the state for one of those users
1. Click "Download All Submissions" again

**Expected:** The zip file would be created again since the submissions have changed since the last time it was created
**Actual:** The already-created zip file is downloaded, and it contains the submission for the student whose state was cleared

The reason for this is the use of [`reset_score`](https://github.com/edx/edx-submissions/blob/master/submissions/api.py#L758) in the function that clears the student state. That API method makes the submission effectively invisible, so even though it was technically 'updated', we can't get its timestamp to see that it was updated after the creation of the last zip file. One solution to this would be to simply delete the zip file if it exists. Triggering the recreation of the zip file might make it easier for the zip creation task to be executed twice concurrently (not sure what effect that would have).

**Comment by amir-qayyum-khan** [comment]
No longer an issue

**Comment by amir-qayyum-khan** [comment]
merged https://github.com/mitodl/edx-sga/pull/239
