### ISSUE TITLE
Student submission file collisions 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#229]
### Steps to reproduce

1. Navigate to an SGA problem with one account (e.g. a student). 
2. Upload a PDF file
3. Navigate to the same SGA problem with a different account (e.g. staff). 
4. Upload another PDF file. 
5. Click Grade Submissions to open the Grading interface. Note that there should be two rows, with two different file names. 
6. Click the link for each submission file to download them. 

### Expected behavior

- You should download two different files, each the same as when they were uploaded. 

### Actual behavior

- Although the two files will have different files names, they will have the same contents.

**Comment by pdpinch** [comment]
This collision behavior occurs also in the zip files.

**Comment by pdpinch** [comment]
I'm kind of guessing, but I suspect this regression has something to do with moving this block:

https://github.com/mitodl/edx-sga/blob/24612d51acdf86ea16a9404ed9d4ea6e9b83d86e/edx_sga/sga.py#L251-L257

before this block:

https://github.com/mitodl/edx-sga/blob/24612d51acdf86ea16a9404ed9d4ea6e9b83d86e/edx_sga/sga.py#L258-L260

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you take a look at this? 

We need to get this working as soon as possible. I would like to add some tests for this issue, but that could be a follow-up PR.

**Comment by amir-qayyum-khan** [comment]
i am testing,
