### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#250]
2019 is the last year of Python 2 support. EdX has plans to upgrade to Python 3.x and Django 2.x. This xBlock needs to be updated as well.

**Comment by pdpinch** [comment]
@noisecapella @tasawernawaz I'm not sure if we can start working on this yet? Does edX support for Python 3 and django 2 need to be in place before we can run Python 3 in tests?

**Comment by tasawernawaz** [comment]
@pdpinch  What does Python 3 in tests mean? Do we want to upgrade this xblock before edx upgrade?

**Comment by noisecapella** [comment]
@pdpinch I'm not sure. We can try to enable Python 3 and see if the tests still pass with tox and Django 2. We could be stuck if there are edx-platform changes which need to be made for any of the code paths our tests touch of theirs, but it may still be useful to make sure there's nothing on our side which is blocking Python 3 adoption

**Comment by pdpinch** [comment]
What happens if we just add another test envrionment in tox?
