### ISSUE TITLE
Juniper compatibility

### ISSUE THREAD

**Issue by toxinu** [mitodl/edx-sga#265]
Hi there,

I wanted to know if `edx-sga` xBlock is already Juniper (Python 3 and Django 2.2) compatible and if not, is there any plan to update it for Juniper? Or are you open to contributions?

Thanks.

**Comment by pdpinch** [comment]
Hi @toxinu. We thought it was updated for Python 3 and Django 2.2 by PR #256 but we recently found some issues with that. 

We fixed one of the problems in #264, but there is still #266.

**Comment by toxinu** [comment]
Thanks for your answer @pdpinch  :)
