### ISSUE TITLE
Incorrect text rendering in Juniper lms

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#266]
### Steps to Reproduce

1. Add "edx-sga" to the Advanced Modules List section of the course advanced settings.
2. In the course outline, add a new "Advanced" Component to a Unit and choose the "Staff Grades Assignment" option.
3. Publish the unit. 
4. Click "View LIve Version"

### Expected results

- The SGA xBlock looks essentially the same in LMS as it does in Studoi. 

### Actual results

<img width="764" alt="image" src="https://user-images.githubusercontent.com/430126/81515654-200b0700-9303-11ea-9d0a-7ff6db455096.png">

**Comment by ahmed-belal** [comment]
Fix is already in, I think we need to create a new release and make sure `edx-platform` is updated to reflect the new version in its requirements. @annagav is already looking into the `edx-platform` requirement update.

**Comment by pdpinch** [comment]
This was fixed in [release 0.11.0](https://github.com/mitodl/edx-sga/releases/tag/v0.11.0)
