### ISSUE TITLE
Incorrect version in __init__.py

### ISSUE THREAD

**Issue by pakaponk** [mitodl/edx-sga#271]
v0.11.0 has already been released but the version specify at [__init__.py](https://github.com/mitodl/edx-sga/blob/master/edx_sga/__init__.py) is still 0.10.0.

Should we change it?

**Comment by pdpinch** [comment]
Oops. Our release script is supposed to take care of that. 

If you’d like to open a PR, we will merge it and update the release.

**Comment by pakaponk** [comment]
Just sent a PR. TBH, I am not familiar with how the python package work.
Not sure whether changing the version at this file is enough.

**Comment by noisecapella** [comment]
Our release script should have taken care of this, but during that particular release there was a bug in the slack bot so we did it manually, and missed a step updating the version number here.

**Comment by pdpinch** [comment]
@pakaponk we just made a new release that includes your fix. Please let us know if you encounter any issues.
