### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/edx-sga#343]
In the latest release Open edX (e.g. `palm`) there are some components that are now refactored and/or deleted and those are still being used in edx-sga. Some of those are [get_module_system_for_user](https://github.com/mitodl/edx-sga/blob/master/edx_sga/tests/integration_tests.py#L86) and xModule.

#### What to do?

We should refactor our tests to not use these components, instead, they should be using the latest components from edX. We did a similar refactoring in https://github.com/mitodl/rapid-response-xblock/pull/139. Which can be used as a reference while refactoring the tests here as well.

**Comment by Anas12091101** [comment]
@arslanashraf7 , I think we can now close this issue?
