### ISSUE TITLE
'StaffGradedAssignmentXBlockWithMixins' object has no attribute 'published_date'

### ISSUE THREAD

**Issue by echanna** [mitodl/edx-sga#35]
Having installed the Staff Graded Assignment XBlock I can upload a file as a student. However when I login as a Teacher I cannot preview the edx-sga xblock in the teacher profile. Instead I get:

'StaffGradedAssignmentXBlockWithMixins' object has no attribute 'published_date'

This is my Log:

Request Method: GET
Request URL:    http://localhost:8000/courses/edX/DemoX/Demo_Course/courseware/interactive_demonstrations/d4faac500623426c941931724d8e9f42/
Django Version: 1.4.12
Exception Type: AttributeError
Exception Value:  
'StaffGradedAssignmentXBlockWithMixins' object has no attribute 'published_date'
Exception Location: /edx/app/edxapp/venvs/edxapp/src/edx-sga/edx_sga/sga.py in update_staff_debug_context, line 191
Python Executable:  /edx/app/edxapp/venvs/edxapp/bin/python
Python Version: 2.7.3
Python Path:  
['.',
 '.',
 '/edx/app/edxapp/edx-platform',
 '/edx/app/edxapp/venvs/edxapp/src/django-staticfiles',
 '/edx/app/edxapp/venvs/edxapp/src/django-pipeline',
 '/edx/app/edxapp/venvs/edxapp/src/django-wiki',
 '/edx/app/edxapp/venvs/edxapp/src/lettuce',
 '/edx/app/edxapp/venvs/edxapp/src/pystache-custom',
 '/edx/app/edxapp/venvs/edxapp/src/zendesk',
 '/edx/app/edxapp/venvs/edxapp/src/django-ipware',
 '/edx/app/edxapp/venvs/edxapp/src/pygeoip',
 '/edx/app/edxapp/venvs/edxapp/src/xblock',
 '/edx/app/edxapp/venvs/edxapp/src/codejail',
 '/edx/app/edxapp/venvs/edxapp/src/diff-cover',
 '/edx/app/edxapp/venvs/edxapp/src/js-test-tool',
 '/edx/app/edxapp/venvs/edxapp/src/django-waffle',
 '/edx/app/edxapp/venvs/edxapp/src/event-tracking',
 '/edx/app/edxapp/venvs/edxapp/src/bok-choy',
 '/edx/app/edxapp/venvs/edxapp/src/django-splash',
 '/edx/app/edxapp/venvs/edxapp/src/acid-xblock',
 '/edx/app/edxapp/venvs/edxapp/src/edx-ora2',
 '/edx/app/edxapp/venvs/edxapp/src/opaque-keys',
 '/edx/app/edxapp/venvs/edxapp/src/ease',
 '/edx/app/edxapp/venvs/edxapp/src/i18n-tools',
 '/edx/app/edxapp/edx-platform/common/lib/calc',
 '/edx/app/edxapp/edx-platform/common/lib/capa',
 '/edx/app/edxapp/edx-platform/common/lib/chem',
 '/edx/app/edxapp/edx-platform/common/lib/sandbox-packages',
 '/edx/app/edxapp/edx-platform/common/lib/symmath',
 '/edx/app/edxapp/edx-platform/common/lib/xmodule',
 '/edx/app/edxapp/venvs/edxapp/src/djpyfs',
 '/edx/app/edxapp/venvs/edxapp/src/edx-jsme',
 '/edx/app/edxapp/venvs/edxapp/src/edx-analytics-data-api-client',
 '/edx/app/edxapp/venvs/edxapp/src/edx-sga',
 '/edx/app/edxapp/venvs/edxapp/lib/python2.7',
 '/edx/app/edxapp/venvs/edxapp/lib/python2.7/plat-linux2',
 '/edx/app/edxapp/venvs/edxapp/lib/python2.7/lib-tk',
 '/edx/app/edxapp/venvs/edxapp/lib/python2.7/lib-old',
 '/edx/app/edxapp/venvs/edxapp/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages',
 '/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/newrelic-2.18.1.15',
 '/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info',
 '/edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info',
 path(u'/edx/app/edxapp/edx-platform'),
 path(u'/edx/app/edxapp/edx-platform/lms/djangoapps'),
 path(u'/edx/app/edxapp/edx-platform/common/djangoapps'),
 path(u'/edx/app/edxapp/edx-platform/common/lib')]
Server time:    Fri, 5 Sep 2014 14:29:45 -0400

**Comment by pdpinch** [comment]
Hi @echanna was this issue fixed by re-installing?

**Comment by echanna** [comment]
Hi thanks for your reply. I have gotten your XBlock working multiple times by following instructions more closely.  I work with these instructions as well as yours: http://www.dangtrinh.com/2014/07/edx-platform-how-to-enable-edx-sga.html
