### ISSUE TITLE
Add support for Django 4.x and remove all deprecation warning

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/edx-sga#352]
### Description/Context

edX has shifted towards using Django 4.x and we should also look to add support for that in this xBlock as well. However, this block doesn't explicitly define a Dajngo version so the installation itself might not be a problem.

However, We might see issues or deprecation warnings from this xBlock since there are things that are either removed or deprecated in Django 4.x and the following releases.

### Plan/Design

- See the upgrade notes [Django 4.x](https://docs.djangoproject.com/en/5.0/releases/4.0/). But the 4.0 version had some security vulnerabilities so we should check this xBlock with [Django 4.2.x](https://docs.djangoproject.com/en/4.2/releases/4.0/)
- Check for any code that is deprecated or removed in Django 4 and refactor it.
- Update tox to run tests against Django42 as well
- Check for any warnings from Django or edX. One example of a warning I am seeing is 
 
```python
2024-01-25 23:05:12,947 WARNING 644 [py.warnings] [user 3] [ip 192.168.65.1] warnings.py:109 - /edx/src/edx-sga/edx_sga/sga.py:37: DeprecatedPackageWarning: Please use import xblock.utils.studio_editable instead of xblockutils.studio_editable because the 'xblock-utils' package has been deprecated and migrated to within 'xblock' package. 
  from xblockutils.studio_editable import StudioEditableXBlockMixin

```

**Comment by arslanashraf7** [comment]
Looks like we already have a PR from the community https://github.com/mitodl/edx-sga/pull/347

**Comment by Anas12091101** [comment]
> Looks like we already have a PR from the community https://github.com/mitodl/edx-sga/pull/347. I've requested them to rebase the PR.

@arslanashraf7 we can then close https://github.com/mitodl/edx-sga/pull/353

**Comment by Anas12091101** [comment]
We can now close this issue
