### ISSUE TITLE
more logging when modifying StudentModule state 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#62]
see https://github.com/mitodl/edx-sga/pull/52#issuecomment-75835580

**Comment by pdpinch** [comment]
@amir-qayyum-arbisoft please attempt this one after #61 

This task is a more open-ended than I would like, so please ask questions if you need to.

**Comment by pdpinch** [comment]
To clarify, this only requires adding logging, not additions to courseware_studentmodulehistory

**Comment by amir-qayyum-arbisoft** [comment]
got it thanks

**Comment by pdpinch** [comment]
closed via #67
