### ISSUE TITLE
set a default display name (and display it in lms)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#71]
extracted from [JIRA OSPR-337](https://openedx.atlassian.net/browse/OSPR-337?focusedCommentId=101991&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-101991)

> Small suggestion here would be to default display name to show for the problem similar to other problems and components in Studio, letting students know they're interacting with a Staff Graded Assignment

> This has broader user facing impact, and thus may be more important than the other suggestions.

**Comment by pdpinch** [comment]
Amir, let me know if there is enough detail here to work on this issue.

**Comment by amir-qayyum-arbisoft** [comment]
@pdpinch it is ok to 

1) Show default display name or display name in case  user has customized it inside studio  (Edit settings)?

2) Show display name below slide bar and above File uploaded text ?

**Comment by pdpinch** [comment]
This would be a default display_name "Staff Graded Assignment" that would display in Studio if the XBlock is edited and there is no value. Any customizations the user made would replace it. 

However, if the display_name is actually empty (i.e. display_name="" in the XML) then it shouldn't display in LMS. 

Does that make sense?

**Comment by amir-qayyum-arbisoft** [comment]
yeah , got it thanks

**Comment by amir-qayyum-arbisoft** [comment]
![display_name](https://cloud.githubusercontent.com/assets/10431250/6662142/50bf9290-cbd9-11e4-9503-e2713c1ce47f.png)

**Comment by pdpinch** [comment]
fixed via #74 

follow-up issue in #75
