### ISSUE TITLE
Multiply assignments for one unit support

### ISSUE THREAD

**Issue by aliaksandrb** [mitodl/edx-sga#88]
Hi!

Here is the situation: we have added two Staff Graded Assignments for one Unit. They displays at LMS correctly. But when user is trying to upload a file for any of them it gets the javascript error:
`Uncaught RangeError: Maximum call stack size exceeded` (Chrome) or `too much recursion` (Firefox), where both points to jquery.min file.

Does multiply assignments for single unit is supported functionality? If it is, seems as a bug for me.

Thanks!

**Comment by aliaksandrb** [comment]
Oh sorry, seems that it is a duplicate of https://github.com/mitodl/edx-sga/issues/81 . Didn't recognize a terminology from first view..

**Comment by carsongee** [comment]
Thanks for reporting anyway.  It is always nice to know there is more demand for a bug fix as it helps us prioritize issues.
