### ISSUE TITLE
Editing Staff Graded Assignment screen cut off title bar and save and cancel button

### ISSUE THREAD

**Issue by maureenkf** [mitodl/edx-sga#89]
We installed the Staff Graded Assignment and when I go to review the settings of the component, the title bar and save and close buttons do not display.  I am unable to apply any changes. Any thoughts on why this would be happening?  I have included a screen shot.

![sga](https://cloud.githubusercontent.com/assets/12073197/7320140/8b31d43a-ea68-11e4-80a9-be4f5fe2c565.png)

**Comment by pdpinch** [comment]
Can you confirm which version of SGA you are using, and which version of Open edX (i.e. Aspen, Birch or something else)?

**Comment by maureenkf** [comment]
Thanks for responding... Where can I go to check what version of SGA and Open edX we are using?

**Comment by maureenkf** [comment]
The fullstack version was installed.  As for the SGA, the directions were followed for GitHub... not sure how we can verify the version..

**Comment by pdpinch** [comment]
Sorry for the delayed reply. 

Regarding the edX version, do you know if you are on "aspen" or "birch" ?

You can find the SGA version by running 

```pip show edx-sga```

I ask because the screenshot you attached looks like it's from an older version of SGA. If you are upgrading, be sure to read the release notes.
