### ISSUE TITLE
Multiple SGA components dont work

### ISSUE THREAD

**Issue by vijay85** [mitodl/edx-sga#91]
When we try to add Multiple SGA components in the same unit for multiple submission, the functionality doesnt work.  Most of the times after selecting a file, the button doesnt get updated with file name nor it gets submitted.

This happens either both of them or sometimes any one of them.

**Comment by carsongee** [comment]
Thanks for the report. This is a known issue, and was reported at https://github.com/mitodl/edx-sga/issues/81.
