### ISSUE TITLE
When upload returns an error, focus should be set to the error message

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sga#92]
> OK, here’s some quick feedback on uploading a file:
> - I can find “"the browse button and press enter on it;
> - I get a standard browser file upload widgit;
> - I choose a file and press “open”;
> - no feedback, and my focus gets completely lost and I have to navigate back to find yet another button which says “upload [filename], what [filename] is the name of the file I thought I just uploaded;
> - once I click this button, no feedback and again focus is undefined;
> - I finally find the “error uploading file” at the end of the unit’s content;

**Comment by amir-qayyum-khan** [comment]
> I can find “"the browse button and press enter on it;
> I get a standard browser file upload widgit;
> I choose a file and press “open”;
> no feedback, and my focus gets completely lost and I have to navigate back to find yet another 
> button which says “upload [filename], what [filename] is the name of the file I thought I just  
>  uploaded;

Already Done till today @pdpinch .

> once I click this button, no feedback and again focus is undefined;
> I finally find the “error uploading file” at the end of the unit’s content;

Opened PR for this.
